from contextlib import asynccontextmanager
from typing import AsyncIterator

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.openapi.docs import get_swagger_ui_html
from starlette.responses import HTMLResponse

from app.api import alerts, dashboard, devices, health, logs, metrics
from app.core.config import get_settings
from app.core.logging import configure_logging
from app.db.database import Base, SessionLocal, engine
from app.services.kafka_consumer import KafkaConsumerWorker
from app.services.seed import seed_alert_rules

configure_logging()
settings = get_settings()
kafka_worker = KafkaConsumerWorker()

OPENAPI_TAGS = [
    {
        "name": "health",
        "description": "Runtime health checks for the API and database connection.",
    },
    {
        "name": "dashboard",
        "description": "Portfolio dashboard aggregates: device status, traffic totals, alert counts, and latest event time.",
    },
    {
        "name": "devices",
        "description": "Device inventory and per-device telemetry detail for routers, switches, firewalls, servers, and services.",
    },
    {
        "name": "metrics",
        "description": "Recent time-series telemetry samples consumed from the Kafka-compatible broker.",
    },
    {
        "name": "alerts",
        "description": "Active/resolved alert records and configurable threshold rules.",
    },
    {
        "name": "logs",
        "description": "Recent structured log events generated by the backend and telemetry producer.",
    },
]


@asynccontextmanager
async def lifespan(_: FastAPI) -> AsyncIterator[None]:
    Base.metadata.create_all(bind=engine)
    with SessionLocal() as db:
        seed_alert_rules(db)
    if settings.enable_kafka_consumer:
        kafka_worker.start()
    yield
    kafka_worker.stop()


app = FastAPI(
    title=settings.app_name,
    version="0.1.0",
    summary="Infrastructure observability API for simulated network, server, service, metric, log, and alert data.",
    description=(
        "InfraPulse ingests simulated infrastructure telemetry through a Kafka-compatible broker, "
        "persists metrics in PostgreSQL, evaluates alert rules, and exposes dashboard-ready REST APIs."
    ),
    contact={"name": "InfraPulse Portfolio Project"},
    openapi_tags=OPENAPI_TAGS,
    docs_url=None,
    redoc_url=None,
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.allowed_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(health.router)
app.include_router(dashboard.router)
app.include_router(devices.router)
app.include_router(metrics.router)
app.include_router(alerts.router)
app.include_router(logs.router)


@app.get("/docs", include_in_schema=False)
def custom_swagger_ui_html() -> HTMLResponse:
    html = get_swagger_ui_html(
        openapi_url=app.openapi_url,
        title="InfraPulse API Docs",
        swagger_ui_parameters={
            "defaultModelsExpandDepth": -1,
            "displayRequestDuration": True,
            "docExpansion": "list",
            "tryItOutEnabled": True,
        },
    )
    return HTMLResponse(
        html.body.decode("utf-8").replace(
            "</head>",
            """
            <style>
              .swagger-ui .info .link { display: none !important; }
              .swagger-ui .info { margin: 32px 0 24px; }
              .swagger-ui .info .title { color: #111827; }
            </style>
            </head>
            """,
        )
    )
